"""Static finance readout; dollar figures are synthetic, never business claims."""
from html import escape


def render(r):
    def table(headers, rows):
        return '<div class="scroll"><table><thead><tr>'+''.join(f'<th>{escape(h)}</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{escape(str(c))}</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
    money=lambda n:f'${n:,.0f}'
    f=r['forecast']; chosen=f['selected']; b=r['margin_bridge']
    bridge=table(['Driver','Contribution to margin change'],[(k,money(v)) for k,v in b['effects'].items()]+[('Total change',money(b['change']))])
    scores=table(['Method','Selection WAPE','Holdout WAPE','Holdout margin MAE'],[(m,f'{f["selection"][m]["wape"]:.1%}',f'{s["wape"]:.1%}',money(s['margin_mae'])) for m,s in f['holdout'].items()])
    cohorts=table(['First purchase cohort','Buyers','90-day repeat rate'],[(c['cohort'],c['buyers'],f'{c["rate"]:.1%}' if c['mature'] else 'Not mature — excluded') for c in r['cohorts']])
    scenarios=table(['Scenario','Revenue','Contribution margin'],[(s['name'],money(s['revenue']),money(s['margin'])) for s in f['scenarios']])
    maximum=max(m['revenue'] for m in r['months'])
    bars=''.join(f'<div class="barrow"><span>{m["month"]}</span><div class="bar" style="width:{m["revenue"]/maximum*100:.2f}%"></div><span>{money(m["revenue"])}</span></div>' for m in r['months'])
    return f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Revenue & margin observatory</title><style>body{{background:#f5f4f0;color:#192f38;font:17px/1.6 system-ui;margin:0}}main{{max-width:1080px;margin:auto;padding:32px 20px}}h1{{font-size:clamp(32px,5vw,50px);line-height:1.1}}.label{{font-weight:750;color:#8d3900}}section{{background:white;padding:24px;margin:24px 0;border:1px solid #d5dbdc;border-radius:12px}}table{{width:100%;border-collapse:collapse;text-align:left}}td,th{{padding:10px;border-bottom:1px solid #d5dbdc}}.scroll{{overflow:auto}}.barrow{{display:grid;grid-template-columns:70px 1fr 85px;align-items:center;gap:10px;font-size:13px;margin:7px 0}}.bar{{height:15px;background:#167264;border-radius:2px}}a{{color:#126454}}code{{overflow-wrap:anywhere}}</style>
<main><p class="label">INDEPENDENT PORTFOLIO · ENTIRELY SYNTHETIC</p><h1>Growth, retention, and the economics behind them.</h1>
<p>{r['orders']:,} invented orders across 24 complete months. Revenue alone does not describe contribution margin. This readout separates volume, mix, pricing and variable cost, then challenges a forecast against simple baselines.</p>
<section><h2>What changed in the latest month?</h2><p>Contribution margin moved from {money(b['before'])} to {money(b['after'])}. The exact Shapley bridge averages all driver orderings; it is an accounting allocation, not a causal estimate.</p>{bridge}<p>Revenue bridge: {money(r['revenue_bridge']['before'])} → {money(r['revenue_bridge']['after'])}. Both bridges reconcile to totals within floating-point tolerance.</p></section>
<section><h2>Monthly net revenue</h2><p>USD; discounts deducted, tax excluded. Variable costs include product and fulfillment costs. Fixed overhead is excluded.</p><div role="img" aria-label="24 monthly synthetic revenue bars with labeled dollar amounts">{bars}</div></section>
<section><h2>Forecast: earn the right to add complexity</h2><p>Frozen choice: <strong>{chosen}</strong>. Select on months 13–18, then evaluate rolling one-month forecasts on months 19–24. Every prediction uses only prior months. Holdout WAPE: <strong>{f['holdout'][chosen]['wape']:.1%}</strong>. Next-month selected revenue forecast: {money(f['next_month']['revenue'])}.</p>{scores}<p>WAPE = total absolute error / total actual revenue. Six holdout months cannot establish reliable seasonality or production accuracy. These errors describe this artificial series only.</p><h3>Finance scenarios</h3>{scenarios}<p>{escape(f['scenario_basis'])}</p></section>
<section><h2>Repeat purchase: respect follow-up</h2><p>Distinct later purchase within 90 days of first observed purchase. Entire calendar cohorts need 90 days of follow-up after month-end; incomplete cohorts show no rate. Same-day orders are not treated as repeat days.</p>{cohorts}</section>
<section><h2>Decision and next investigation</h2><p>Use the driver bridge to prioritize checks of product mix, discounting and fulfillment cost. Validate those inputs before proposing pricing changes. This fixture cannot identify real customer needs or predict a business outcome.</p><p>The generator deliberately shifts mix, price and cost after month 18. This stress-tests forecasting under a regime change; it is not discovered market behavior. Refund timing, multi-item baskets, currencies, acquisition cost, stockouts, subscriptions and customer identity resolution are outside this example.</p><p>Run <code>python -m observatory.finance</code>; inspect <a href="results.json">aggregate evidence</a> and <code>sql/finance.sql</code>. No credentials or cloud service are needed.</p></section></main></html>'''
